### ISSUE TITLE
Connect Users with Groups

### ISSUE THREAD

**Issue by putriz** [WhenIsBest/whenisbest#18]
Right now, when someone would sign up to create an account, the groups listed on the homepage are not unique/specific to the user. We need to figure out how to connect each user to his/her own list of groups.

**Comment by helei96** [comment]
Need to improve schema representation (Users: need an id; Create an association table (stores both userIds and groupIds, to associate users with their groups); Groups: needs an id, can probably scrap the "group members" attribute; Need a calendars; Events: needs id, should be endtime instead of duration.)
 and figure out how ruby exactly handles the database (SQLight files written how and where?)
